name: squad
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - ujson
  - numpy=1.16.6
  - pip
  - spacy=2.0.16
  - tensorboard
  - tensorflow
  - tensorboardX
  - tqdm
  - urllib3
  - pytorch=1.4.0
  - jupyter
  - ipython
  - pip:
    - torch==1.4.0
    - transformers
